### PR TITLE
Make actions work with centered

### PR DESCRIPTION
**Pull request by ekhaled**
`Actions` addon does not work with `Centered` addon.
This is because events are not passed through to the inner component.

This PR fixes that by keeping a reference to the original component and attaching the event handlers to the original component.
It then mounts the original component into a `slot` of the wrapper component provided by the `Centered` addon.

This approach makes it trivial to implement other addons that might need to wrap the original component in this way.

I have tested this as much as possible, but please do check from your side too.

I think if you merge this PR to this branch, it will get added to the PR on the storybooks repo.

### CODE REVIEW

**Comment by ekhaled** [comment]
@plumpNation let me know if you have any questions on this. Or if you would like me to change anything.

**Comment by plumpNation** [comment]
Hey there! Thanks so much for catching this. Maybe you could add to the centered addons stories, and take a little credit in the output too :D

```
import { action } from '@storybook/addon-actions';
...

.add('with action', () => ({
    Component: Button,
    on: {
      click: action(`Tell me it ain't so! Centered and with actions! Thanks @ekhaled :)`),
    },
  }));
```

**Review by plumpNation — APPROVED** [review]

**Comment by ekhaled** [comment]
Thanks for merging PR.
I'll let you do the examples 😄

**Comment by plumpNation** [comment]
A modest man.

**Pull request merged**
